name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://dl-pc-sz-cf.pds.quark.cn/fe234f92e80548289fe2502ff70cf8315d81e510/5d81e510d36d8af71e9a44bbb9d5346e065c0233?Expires=1689490002&OSSAccessKeyId=LTAIyYfxTqY7YZsg&Signature=SiV6uUfTC88Z64hTnl%2Fg4NaiMRs%3D&x-oss-traffic-limit=503316480&response-content-disposition=attachment%3B%20filename%3Dmiui_MIPAD4_9.8.29_6647b25a58_8.1.zip&callback-var=eyJ4OnNwIjoiMTk5IiwieDp0b2tlbiI6IjItZWNlZDIxOWU3NWFmMzM4NjY4NzkwOTFjMWQwYmM5YmEtOC0xLTYxNDQwLTM3NGJiODY0Nzg0ODQxZDliNWU0NGRiMjNmMGEwYTMzLTM5MDE4YzFjODU4MThkMzg1ODkwMTMyNjEwMmNlYWFiIiwieDp0dGwiOiI1Njk4MCJ9&callback=eyJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24vanNvbiIsImNhbGxiYWNrU3RhZ2UiOiJiZWZvcmUtZXhlY3V0ZSIsImNhbGxiYWNrRmFpbHVyZUFjdGlvbiI6Imlnbm9yZSIsImNhbGxiYWNrVXJsIjoiaHR0cHM6Ly9jbG91ZC1hdXRoLmRyaXZlLnF1YXJrLmNuL291dGVyL29zcy9jaGVja3BsYXkiLCJjYWxsYmFja0JvZHkiOiJ7XCJob3N0XCI6JHtodHRwSGVhZGVyLmhvc3R9LFwic2l6ZVwiOiR7c2l6ZX0sXCJyYW5nZVwiOiR7aHR0cEhlYWRlci5yYW5nZX0sXCJyZWZlcmVyXCI6JHtodHRwSGVhZGVyLnJlZmVyZXJ9LFwiY29va2llXCI6JHtodHRwSGVhZGVyLmNvb2tpZX0sXCJtZXRob2RcIjoke2h0dHBIZWFkZXIubWV0aG9kfSxcImlwXCI6JHtjbGllbnRJcH0sXCJvYmplY3RcIjoke29iamVjdH0sXCJzcFwiOiR7eDpzcH0sXCJ0b2tlblwiOiR7eDp0b2tlbn0sXCJ0dGxcIjoke3g6dHRsfSxcImNsaWVudF90b2tlblwiOiR7cXVlcnlTdHJpbmcuY2xpZW50X3Rva2VufX0ifQ%3D%3D&ud=16-2-5-4-7-N-4-N-1-16" -o "miui_MIPAD4_9.8.29_6647b25a58_8.1.zip" -b "b-user-id=a20cdadc-aa61-6a01-5f57-17f6852d1337; __kps=AAS9pkvWHXjJzTHMCIq9ie1C; __ktd=jUBTjScuQEq3Q+8Qj078bg==; __uid=AAS9pkvWHXjJzTHMCIq9ie1C; __kp=d7e454c0-1c54-11ee-8e28-5de17f323210; ctoken=VvHF0rmpWm-OiDJ33s_4U0dq; __chkey=; __wpkreporterwid_=32adea44-9954-49cc-89ae-c9d5e3fb20fe; __itrace_wid=2139dccc-a9a9-4057-04c1-2ed3f70fc42b; __puus=7b6ca666243d9651b3efb346329e5888AATRLKtb8rgf0lowrntJ4o65fJYRe1xDTGcxyUvh2yD2Rj8NMPVoxhGE8ciGq1U73pf106Gvsp7TINbXBvWyIj1tUBfEZXI4CaU5ramFrsLS9oD//85pZPFPgaxOkEMOd7sjm0GWCaQ7XfUd97BD6BNYZEBhnAVbtI5osbE8WDkWnPsioX+o9rDOVUocACEgHAhBKfzaKEwAVBmPUQeK6Qwa
  ROM_NAME: MIUI
  BUILD_TYPE: a
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
